name: Deploying to VPS

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: SSH setup and run commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ./deploy/${{ github.event.repository.name }}
            git pull
            docker rm --force ${{ github.event.repository.name  }}-deploy || true
            docker build -t ${{ github.event.repository.owner.name }}/${{ github.event.repository.name  }}:${{ github.sha }} --quiet .
            docker run --detach --name ${{ github.event.repository.name  }}-deploy ${{ github.event.repository.owner.name }}/${{ github.event.repository.name  }}:${{ github.sha }}
            docker container prune --force && docker image prune --all --force
